# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins: 
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            'Nicolas Pavie'
tagline:          ''
description:      'Software engineer @ <a href="https://www.avh.asso.fr"><img src="https://www.avh.asso.fr/sites/all/themes/custom/customer/images/logo-home.png" alt="Association Valentin Haüy"/></a>'
url:              https://npavie.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/npavie
