# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins: 
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Nicolas Pavie'
tagline:          ''
description:      'Software engineer @ <br/><a href="https://braillenet.org"><img src="https://www.braillenet.org/wp-content/themes/braillenet/img/logo-braillenet.png"/></a>'
url:              http://npavie.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/npavie
